import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'dukaansaathi-language';

const messages = {
  en: {
    English: 'English',
    Hindi: 'Hindi',
    Kannada: 'Kannada',
    Home: 'Home',
    Dashboard: 'Dashboard',
    Back: 'Back',
    Login: 'Login',
    Logout: 'Logout',
    'Logged out successfully': 'Logged out successfully',
    'Hi, {name}': 'Hi, {name}',
    'Toggle navigation menu': 'Toggle navigation menu',
    'Go back': 'Go back',
    Warning: 'Warning',
    'Dismiss notification': 'Dismiss notification',
    'Welcome to DukaanSaathi': 'Welcome to DukaanSaathi',
    'Loading your shopping experience...': 'Loading your shopping experience...',
    '3D effects disabled on this device': '3D effects disabled on this device',
    'Run Your Shop Smarter with AI': 'Run Your Shop Smarter with AI',
    'Select your preferred language': 'Select your preferred language',
    'Language selector': 'Language selector',
    'Get Started': 'Get Started',
    "By continuing, you agree to DukaanSaathi's Terms of Service and Privacy Policy.": "By continuing, you agree to DukaanSaathi's Terms of Service and Privacy Policy.",
    'Built for modern retailers': 'Built for modern retailers',
    'Inventory, billing, and AI recommendations in one workflow.': 'Inventory, billing, and AI recommendations in one workflow.',
    'Browse Products': 'Browse Products',
    'Welcome back!': 'Welcome back!',
    'Login failed. Please try again.': 'Login failed. Please try again.',
    'Account created! Welcome to DukaanSaathi.': 'Account created! Welcome to DukaanSaathi.',
    'Registration failed. Please try again.': 'Registration failed. Please try again.',
    'Create Account': 'Create Account',
    'Sign In': 'Sign In',
    'Create Retailer Account': 'Create Retailer Account',
    'Register with your email to manage your shop with DukaanSaathi.': 'Register with your email to manage your shop with DukaanSaathi.',
    'Full Name': 'Full Name',
    Email: 'Email',
    Password: 'Password',
    'Your full name': 'Your full name',
    'Min. 6 characters': 'Min. 6 characters',
    'Creating account...': 'Creating account...',
    'Already have an account?': 'Already have an account?',
    'Retailer Sign In': 'Retailer Sign In',
    'Sign in to manage your retail shop.': 'Sign in to manage your retail shop.',
    'Enter your email': 'Enter your email',
    'Enter your password': 'Enter your password',
    'Signing in...': 'Signing in...',
    'New here?': 'New here?',
    'Create an account': 'Create an account',
    Notifications: 'Notifications',
    'Clear all': 'Clear all',
    Dismiss: 'Dismiss',
    'All clear! No new alerts.': 'All clear! No new alerts.',
    'Dismiss all': 'Dismiss all',
    'Notifications — {count} unread': 'Notifications — {count} unread',
    'GST Planning Reminder': 'GST Planning Reminder',
    'Estimate your quarterly GST liability using Finance AI before month-end to avoid surprises.': 'Estimate your quarterly GST liability using Finance AI before month-end to avoid surprises.',
    Finance: 'Finance',
    'Income Tax Insight': 'Income Tax Insight',
    'New regime: No income tax up to ₹12 lakh. Use Finance AI to simulate your exact tax slab.': 'New regime: No income tax up to ₹12 lakh. Use Finance AI to simulate your exact tax slab.',
    Tax: 'Tax',
    'AI Campaign Ready': 'AI Campaign Ready',
    'Add any product and instantly get AI product photography + a full launch campaign strategy.': 'Add any product and instantly get AI product photography + a full launch campaign strategy.',
    Marketing: 'Marketing',
    'Boost Weekend Sales': 'Boost Weekend Sales',
    'Bundle 2–3 related products as a combo deal — retailers typically see a 15–20% sales lift.': 'Bundle 2–3 related products as a combo deal — retailers typically see a 15–20% sales lift.',
    Tip: 'Tip',
    'Festive Season Strategy': 'Festive Season Strategy',
    'Build WhatsApp broadcast lists now. Festive outreach gets 3× better open rates than email.': 'Build WhatsApp broadcast lists now. Festive outreach gets 3× better open rates than email.',
    'Input GST Credit': 'Input GST Credit',
    'Reconcile your purchase invoices this week to maximise your eligible input GST credit claims.': 'Reconcile your purchase invoices this week to maximise your eligible input GST credit claims.',
    Inventory: 'Inventory',
    'Low Stock: {name}': 'Low Stock: {name}',
    'Only {quantity} unit left. Restock before you run out.': 'Only {quantity} unit left. Restock before you run out.',
    'Only {quantity} units left. Restock before you run out.': 'Only {quantity} units left. Restock before you run out.',
    'You are not authorized to view this page.': 'You are not authorized to view this page.',
    'Failed to load products': 'Failed to load products',
    'Failed to fetch dashboard stats': 'Failed to fetch dashboard stats',
    'Failed to load bills': 'Failed to load bills',
    'Failed to load sales analytics': 'Failed to load sales analytics',
    'Selected product no longer exists. Switched to first available product.': 'Selected product no longer exists. Switched to first available product.',
    'Failed to generate ARIMA forecast': 'Failed to generate ARIMA forecast',
    'Product updated successfully': 'Product updated successfully',
    'Product added successfully': 'Product added successfully',
    'Failed to submit product': 'Failed to submit product',
    'Add or select a product first to generate marketing strategy': 'Add or select a product first to generate marketing strategy',
    'Marketing AI strategy generated': 'Marketing AI strategy generated',
    'Failed to generate marketing advice': 'Failed to generate marketing advice',
    'GST compliance audit ready': 'GST compliance audit ready',
    'Failed to generate financial advice': 'Failed to generate financial advice',
    'Ask DukaanSaathi is temporarily unavailable': 'Ask DukaanSaathi is temporarily unavailable',
    'Product deleted successfully': 'Product deleted successfully',
    'Failed to delete product': 'Failed to delete product',
    '{name} is out of stock!': '{name} is out of stock!',
    'Warning: Only {quantity} {name} left in stock!': 'Warning: Only {quantity} {name} left in stock!',
    'Cannot add more {name}. Only {quantity} available.': 'Cannot add more {name}. Only {quantity} available.',
    'Please enter customer name': 'Please enter customer name',
    'Please add items to the bill': 'Please add items to the bill',
    'Insufficient stock for {name}. Only {quantity} available.': 'Insufficient stock for {name}. Only {quantity} available.',
    'Bill generated successfully! 🎉': 'Bill generated successfully! 🎉',
    'Failed to generate bill': 'Failed to generate bill',
    'Bill downloaded successfully! 📄': 'Bill downloaded successfully! 📄',
    'Bill printed successfully! 🖨️': 'Bill printed successfully! 🖨️',
    'Camera not ready yet. Please wait a second.': 'Camera not ready yet. Please wait a second.',
    'Unable to process camera frame.': 'Unable to process camera frame.',
    'Product scanned and saved to sales.json': 'Product scanned and saved to sales.json',
    'Scanner report generated': 'Scanner report generated',
    'Retail command center': 'Retail command center',
    'Good Morning': 'Good Morning',
    'Good Afternoon': 'Good Afternoon',
    'Good Evening': 'Good Evening',
    'Track revenue, identify your most selling products, and predict demand before stock runs low.': 'Track revenue, identify your most selling products, and predict demand before stock runs low.',
    'Last 14 days': 'Last 14 days',
    'Last 12 weeks': 'Last 12 weeks',
    'Last 12 months': 'Last 12 months',
    'Last 5 years': 'Last 5 years',
    'Analytics Window': 'Analytics Window',
    'Revenue in View': 'Revenue in View',
    'Top Product': 'Top Product',
    'Waiting for sales': 'Waiting for sales',
    'No transactions yet': 'No transactions yet',
    '{count} units sold': '{count} units sold',
    '{count} items sold': '{count} items sold',
    '{count} plotted points': '{count} plotted points',
    "Today's Sales": "Today's Sales",
    'Customers Today': 'Customers Today',
    'Low Stock Items': 'Low Stock Items',
    '{count} items': '{count} items',
    Alert: 'Alert',
    'Sales Trend': 'Sales Trend',
    Day: 'Day',
    Week: 'Week',
    Month: 'Month',
    Year: 'Year',
    'Loading sales charts...': 'Loading sales charts...',
    'No sales data available yet.': 'No sales data available yet.',
    Revenue: 'Revenue',
    'Items Sold': 'Items Sold',
    'Most Selling Products': 'Most Selling Products',
    'Top products will appear after sales start.': 'Top products will appear after sales start.',
    'Qty Sold': 'Qty Sold',
    'Hybrid ARIMA + SARIMA Forecast': 'Hybrid ARIMA + SARIMA Forecast',
    'Select product': 'Select product',
    'Next 7 days': 'Next 7 days',
    'Next 14 days': 'Next 14 days',
    'Next 21 days': 'Next 21 days',
    'Next 30 days': 'Next 30 days',
    'Predicting...': 'Predicting...',
    'Run Hybrid Forecast': 'Run Hybrid Forecast',
    'Method: {method}': 'Method: {method}',
    'Suggested stock for next {days} days:': 'Suggested stock for next {days} days:',
    'Historical Qty': 'Historical Qty',
    'Predicted Qty': 'Predicted Qty',
    'Select a product and run hybrid forecast to view demand prediction.': 'Select a product and run hybrid forecast to view demand prediction.',
    'Income Tax Threshold Crossed!': 'Income Tax Threshold Crossed!',
    'Income Tax Alert — 1 Month Warning': 'Income Tax Alert — 1 Month Warning',
    'Dismiss tax alert': 'Dismiss tax alert',
    'Dismiss expiry alert': 'Dismiss expiry alert',
    'Your FY revenue {annualRevenue} has exceeded the ₹15,00,000 threshold. Estimated income tax payable: {estimatedTax} (New Regime + 4% cess). Please consult a tax advisor.': 'Your FY revenue {annualRevenue} has exceeded the ₹15,00,000 threshold. Estimated income tax payable: {estimatedTax} (New Regime + 4% cess). Please consult a tax advisor.',
    'At your current sales rate, your FY revenue will cross ₹15,00,000 in approximately {daysUntilCross} days. Current FY revenue: {annualRevenue} | Remaining before threshold: {remaining} | Estimated tax at threshold: {estimatedTax} (New Regime + 4% cess).': 'At your current sales rate, your FY revenue will cross ₹15,00,000 in approximately {daysUntilCross} days. Current FY revenue: {annualRevenue} | Remaining before threshold: {remaining} | Estimated tax at threshold: {estimatedTax} (New Regime + 4% cess).',
    'Expiry Alert: Replace These Foods/Beverages Soon': 'Expiry Alert: Replace These Foods/Beverages Soon',
    '{name} ({days} days expired)': '{name} ({days} days expired)',
    '{name} ({days} days left)': '{name} ({days} days left)',
    'and {count} more.': 'and {count} more.',
    'Latest AI Product Photo': 'Latest AI Product Photo',
    'Open Marketing AI': 'Open Marketing AI',
    'Product': 'Product',
    'Ask DukaanSaathi': 'Ask DukaanSaathi',
    'Get instant answers about your inventory, sales, and more.': 'Get instant answers about your inventory, sales, and more.',
    'Ask Now': 'Ask Now',
    'Quick Actions': 'Quick Actions',
    'Create Bill': 'Create Bill',
    'Sales Analytics': 'Sales Analytics',
    'Billing History': 'Billing History',
    'Expiry Alerts': 'Expiry Alerts',
    'New Customer': 'New Customer',
    'Scanning...': 'Scanning...',
    'Scan Product': 'Scan Product',
    'Generating...': 'Generating...',
    'Scan Report': 'Scan Report',
    'Scanner Output': 'Scanner Output',
    'Latest Scan JSON': 'Latest Scan JSON',
    'Latest Report': 'Latest Report',
    'Manage Products': 'Manage Products',
    'Add Product': 'Add Product',
    Image: 'Image',
    Product: 'Product',
    Category: 'Category',
    Price: 'Price',
    Stock: 'Stock',
    GST: 'GST',
    Actions: 'Actions',
    'No Image': 'No Image',
    'Expiry:': 'Expiry:',
    Yes: 'Yes',
    No: 'No',
    'Admin Billing': 'Admin Billing',
    'Create New Bill': 'Create New Bill',
    'All Bills': 'All Bills',
    'Bill ID': 'Bill ID',
    Customer: 'Customer',
    Items: 'Items',
    Subtotal: 'Subtotal',
    Total: 'Total',
    Payment: 'Payment',
    Date: 'Date',
    'Walk-in Customer': 'Walk-in Customer',
    'View Bill': 'View Bill',
    'Download Bill': 'Download Bill',
    'Print Bill': 'Print Bill',
    'Reports & Visualizations': 'Reports & Visualizations',
    'Transaction History': 'Transaction History',
    'Transaction ID': 'Transaction ID',
    Amount: 'Amount',
    'Payment Method': 'Payment Method',
    'Marketing Agent AI': 'Marketing Agent AI',
    'Generate Strategy': 'Generate Strategy',
    'Latest Product:': 'Latest Product:',
    'Price:': 'Price:',
    'Stock:': 'Stock:',
    'Photo Style': 'Photo Style',
    'Studio White': 'Studio White',
    'Dark Luxury': 'Dark Luxury',
    'Lifestyle Desk': 'Lifestyle Desk',
    'Regenerate Product Photo': 'Regenerate Product Photo',
    'Strategy Engine:': 'Strategy Engine:',
    'Objective:': 'Objective:',
    'Target Audience:': 'Target Audience:',
    'Value Hook:': 'Value Hook:',
    'CTA:': 'CTA:',
    'AI Product Photography': 'AI Product Photography',
    'Recommended Channels': 'Recommended Channels',
    'Offer Ideas': 'Offer Ideas',
    'Content Ideas': 'Content Ideas',
    'Add a product and generate a marketing strategy to see campaign suggestions here.': 'Add a product and generate a marketing strategy to see campaign suggestions here.',
    'Website help only. Ask about features, workflows, and troubleshooting in this app.': 'Website help only. Ask about features, workflows, and troubleshooting in this app.',
    'Thinking...': 'Thinking...',
    'Ask about DukaanSaathi website usage': 'Ask about DukaanSaathi website usage',
    Ask: 'Ask',
    'GST Compliance Advisor (India)': 'GST Compliance Advisor (India)',
    'This advisor automatically analyzes your product catalog, billing transactions, GST rates, and inventory-linked sales records. It then gives clear GST compliance recommendations for small Indian businesses.': 'This advisor automatically analyzes your product catalog, billing transactions, GST rates, and inventory-linked sales records. It then gives clear GST compliance recommendations for small Indian businesses.',
    'Analyzing...': 'Analyzing...',
    'Run GST Compliance Audit': 'Run GST Compliance Audit',
    'Compliance Summary ({period})': 'Compliance Summary ({period})',
    'Products analyzed:': 'Products analyzed:',
    'Invoices analyzed:': 'Invoices analyzed:',
    'Taxable turnover:': 'Taxable turnover:',
    'Output GST from invoices:': 'Output GST from invoices:',
    'Potential underpaid GST:': 'Potential underpaid GST:',
    'Potential excess charged GST:': 'Potential excess charged GST:',
    'Rule Coverage': 'Rule Coverage',
    'Coverage:': 'Coverage:',
    '{count}/10 rules applied': '{count}/10 rules applied',
    'All rules covered': 'All rules covered',
    'Review remaining rules': 'Review remaining rules',
    'Compliance Issues': 'Compliance Issues',
    'Compliance Issue:': 'Compliance Issue:',
    'Explanation of Rule:': 'Explanation of Rule:',
    'Risk Level:': 'Risk Level:',
    'Suggested Action:': 'Suggested Action:',
    'Estimated Tax Impact:': 'Estimated Tax Impact:',
    'Regulation:': 'Regulation:',
    'Invoice Rate Mismatch Sample': 'Invoice Rate Mismatch Sample',
    'Transactions Above Rs. 50,000 (E-Way Bill Check)': 'Transactions Above Rs. 50,000 (E-Way Bill Check)',
    'Product Scanner': 'Product Scanner',
    'Use your webcam to scan product labels and store structured JSON in sales.json.': 'Use your webcam to scan product labels and store structured JSON in sales.json.',
    'Processing...': 'Processing...',
    'Generate Report': 'Generate Report',
    'Tip: Open camera, align label, then tap Capture & Scan.': 'Tip: Open camera, align label, then tap Capture & Scan.',
    'Digital Twin View': 'Digital Twin View',
    '3D twin is simplified on this device for better performance.': '3D twin is simplified on this device for better performance.',
    'Store Mirror': 'Store Mirror',
    'Live retail snapshot': 'Live retail snapshot',
    'Use this view to monitor sales momentum, stock pressure, and your top-selling product in one place.': 'Use this view to monitor sales momentum, stock pressure, and your top-selling product in one place.',
    'Revenue in current view': 'Revenue in current view',
    'Recent days': 'Recent days',
    'Selected reporting window': 'Selected reporting window',
    'Top product': 'Top product',
    'No sales yet': 'No sales yet',
    'Start billing to see product demand': 'Start billing to see product demand',
    'Low stock pressure': 'Low stock pressure',
    'Items need restocking soon': 'Items need restocking soon',
    'Inventory looks healthy': 'Inventory looks healthy',
    'Operational Controls': 'Operational Controls',
    'Open Reports': 'Open Reports',
    'Review Stock': 'Review Stock',
    'Add New Product': 'Add New Product',
    'Product Name': 'Product Name',
    'Enter product name': 'Enter product name',
    'Select Category': 'Select Category',
    Description: 'Description',
    'Enter product description': 'Enter product description',
    'Price (₹)': 'Price (₹)',
    'Stock Quantity': 'Stock Quantity',
    'Expiry Date': 'Expiry Date',
    'GST Applicable': 'GST Applicable',
    'Product Image': 'Product Image',
    'Loading admin dashboard...': 'Loading admin dashboard...',
    'Back to dashboard': 'Back to dashboard',
    Reports: 'Reports',
    Scanner: 'Scanner',
    'Quick mobile actions': 'Quick mobile actions',
    'View digital twin': 'View digital twin',
    'Create bill': 'Create bill',
    'Capture Product': 'Capture Product',
    'Close scanner camera': 'Close scanner camera',
    Cancel: 'Cancel',
    'Capture & Scan': 'Capture & Scan',
    'Update Product': 'Update Product',
    'Customer Name *': 'Customer Name *',
    'Enter customer name': 'Enter customer name',
    'Sale Date *': 'Sale Date *',
    'Customer Phone': 'Customer Phone',
    'Enter customer phone': 'Enter customer phone',
    'Customer Email': 'Customer Email',
    'Enter customer email': 'Enter customer email',
    cash: 'Cash',
    card: 'Card',
    upi: 'UPI',
    bank_transfer: 'Bank Transfer',
    'Apply GST (18%)': 'Apply GST (18%)',
    'Add Products': 'Add Products',
    'Select a product to add': 'Select a product to add',
    'No items added yet. Select products above to add them.': 'No items added yet. Select products above to add them.',
    '₹{price} each': '₹{price} each',
    Notes: 'Notes',
    'Any additional notes...': 'Any additional notes...',
    'Generate Bill': 'Generate Bill',
    Close: 'Close',
    'Quality Products & Gifts': 'Quality Products & Gifts',
    Time: 'Time',
    Phone: 'Phone',
    'No items found': 'No items found',
    TOTAL: 'TOTAL',
    'Thank you for shopping with DukaanSaathi!': 'Thank you for shopping with DukaanSaathi!',
    'Visit us again for more amazing products': 'Visit us again for more amazing products',
    'Contact: +91 XXXXXXXXXX | Email: info@dukaansaathi.com': 'Contact: +91 XXXXXXXXXX | Email: info@dukaansaathi.com',
    'Correct GST slab per product': 'Correct GST slab per product',
    'Incorrect GST rate in invoices': 'Incorrect GST rate in invoices',
    'Missing or incorrect HSN codes': 'Missing or incorrect HSN codes',
    'GST registration threshold eligibility': 'GST registration threshold eligibility',
    'Composition scheme eligibility': 'Composition scheme eligibility',
    'E-Way bill requirement above Rs. 50,000': 'E-Way bill requirement above Rs. 50,000',
    'Input Tax Credit opportunities': 'Input Tax Credit opportunities',
    'Filing obligations (GSTR-1 and GSTR-3B)': 'Filing obligations (GSTR-1 and GSTR-3B)',
    'Tax risk or penalty exposure': 'Tax risk or penalty exposure',
    'Actionable compliance steps': 'Actionable compliance steps',
  },
  hi: {
    English: 'अंग्रेज़ी', Hindi: 'हिंदी', Kannada: 'कन्नड़', Home: 'होम', Dashboard: 'डैशबोर्ड', Back: 'वापस', Login: 'लॉगिन', Logout: 'लॉगआउट',
    'Logged out successfully': 'सफलतापूर्वक लॉगआउट किया गया', 'Hi, {name}': 'नमस्ते, {name}', 'Toggle navigation menu': 'नेविगेशन मेनू खोलें', 'Go back': 'वापस जाएँ', Warning: 'चेतावनी', 'Dismiss notification': 'सूचना हटाएँ',
    'Welcome to DukaanSaathi': 'DukaanSaathi में आपका स्वागत है', 'Loading your shopping experience...': 'आपका शॉपिंग अनुभव लोड हो रहा है...', '3D effects disabled on this device': 'इस डिवाइस पर 3D प्रभाव बंद हैं',
    'Run Your Shop Smarter with AI': 'AI के साथ अपनी दुकान को और स्मार्ट चलाएँ', 'Select your preferred language': 'अपनी पसंदीदा भाषा चुनें', 'Language selector': 'भाषा चयन', 'Get Started': 'शुरू करें',
    "By continuing, you agree to DukaanSaathi's Terms of Service and Privacy Policy.": 'जारी रखकर आप DukaanSaathi की सेवा शर्तों और गोपनीयता नीति से सहमत होते हैं।',
    'Built for modern retailers': 'आधुनिक रिटेलर्स के लिए बनाया गया', 'Inventory, billing, and AI recommendations in one workflow.': 'इन्वेंटरी, बिलिंग और AI सुझाव एक ही वर्कफ़्लो में।', 'Browse Products': 'उत्पाद देखें',
    'Welcome back!': 'वापसी पर स्वागत है!', 'Login failed. Please try again.': 'लॉगिन विफल रहा। कृपया फिर प्रयास करें।', 'Account created! Welcome to DukaanSaathi.': 'खाता बन गया! DukaanSaathi में आपका स्वागत है।', 'Registration failed. Please try again.': 'पंजीकरण विफल रहा। कृपया फिर प्रयास करें।',
    'Create Account': 'खाता बनाएँ', 'Sign In': 'साइन इन', 'Create Retailer Account': 'रिटेलर खाता बनाएँ', 'Register with your email to manage your shop with DukaanSaathi.': 'DukaanSaathi के साथ अपनी दुकान प्रबंधित करने के लिए ईमेल से पंजीकरण करें।', 'Full Name': 'पूरा नाम', Email: 'ईमेल', Password: 'पासवर्ड', 'Your full name': 'आपका पूरा नाम', 'Min. 6 characters': 'कम से कम 6 अक्षर', 'Creating account...': 'खाता बनाया जा रहा है...', 'Already have an account?': 'क्या आपके पास पहले से खाता है?', 'Retailer Sign In': 'रिटेलर साइन इन', 'Sign in to manage your retail shop.': 'अपनी रिटेल दुकान प्रबंधित करने के लिए साइन इन करें।', 'Enter your email': 'अपना ईमेल दर्ज करें', 'Enter your password': 'अपना पासवर्ड दर्ज करें', 'Signing in...': 'साइन इन हो रहा है...', 'New here?': 'नए हैं?', 'Create an account': 'खाता बनाएँ',
    Notifications: 'सूचनाएँ', 'Clear all': 'सब साफ करें', Dismiss: 'हटाएँ', 'All clear! No new alerts.': 'सब ठीक है! कोई नई सूचना नहीं।', 'Dismiss all': 'सभी हटाएँ', 'Notifications — {count} unread': 'सूचनाएँ — {count} अपठित',
    'GST Planning Reminder': 'GST योजना स्मरण', 'Estimate your quarterly GST liability using Finance AI before month-end to avoid surprises.': 'महीने के अंत से पहले Finance AI से अपनी तिमाही GST देनदारी का अनुमान लगाएँ।', Finance: 'वित्त', 'Income Tax Insight': 'आयकर जानकारी', 'New regime: No income tax up to ₹12 lakh. Use Finance AI to simulate your exact tax slab.': 'नई व्यवस्था: ₹12 लाख तक आयकर नहीं। अपना सटीक टैक्स स्लैब देखने के लिए Finance AI का उपयोग करें।', Tax: 'कर', 'AI Campaign Ready': 'AI अभियान तैयार', 'Add any product and instantly get AI product photography + a full launch campaign strategy.': 'कोई भी उत्पाद जोड़ें और तुरंत AI उत्पाद फोटोग्राफी तथा पूरा लॉन्च अभियान पाएँ।', Marketing: 'मार्केटिंग', 'Boost Weekend Sales': 'वीकेंड बिक्री बढ़ाएँ', 'Bundle 2–3 related products as a combo deal — retailers typically see a 15–20% sales lift.': '2–3 संबंधित उत्पादों का कॉम्बो ऑफर बनाएँ — रिटेलर्स को सामान्यतः 15–20% बिक्री बढ़त मिलती है।', Tip: 'टिप', 'Festive Season Strategy': 'त्योहारी रणनीति', 'Build WhatsApp broadcast lists now. Festive outreach gets 3× better open rates than email.': 'अभी WhatsApp प्रसारण सूची बनाइए। त्योहारों में WhatsApp की ओपन रेट ईमेल से 3 गुना बेहतर होती है।', 'Input GST Credit': 'इनपुट GST क्रेडिट', 'Reconcile your purchase invoices this week to maximise your eligible input GST credit claims.': 'इस सप्ताह अपने खरीद चालानों का मिलान करें ताकि पात्र इनपुट GST क्रेडिट अधिकतम हो सके।', Inventory: 'इन्वेंटरी', 'Low Stock: {name}': 'कम स्टॉक: {name}', 'Only {quantity} unit left. Restock before you run out.': 'केवल {quantity} यूनिट बची है। खत्म होने से पहले स्टॉक भरें।', 'Only {quantity} units left. Restock before you run out.': 'केवल {quantity} यूनिट बची हैं। खत्म होने से पहले स्टॉक भरें।',
    'You are not authorized to view this page.': 'आप इस पेज को देखने के लिए अधिकृत नहीं हैं।', 'Failed to load products': 'उत्पाद लोड नहीं हो सके', 'Failed to fetch dashboard stats': 'डैशबोर्ड आँकड़े नहीं मिल सके', 'Failed to load bills': 'बिल लोड नहीं हो सके', 'Failed to load sales analytics': 'सेल्स एनालिटिक्स लोड नहीं हो सका', 'Selected product no longer exists. Switched to first available product.': 'चयनित उत्पाद अब मौजूद नहीं है। पहले उपलब्ध उत्पाद पर स्विच किया गया।', 'Failed to generate ARIMA forecast': 'ARIMA पूर्वानुमान नहीं बन सका', 'Product updated successfully': 'उत्पाद सफलतापूर्वक अपडेट हुआ', 'Product added successfully': 'उत्पाद सफलतापूर्वक जोड़ा गया', 'Failed to submit product': 'उत्पाद जमा नहीं हो सका', 'Add or select a product first to generate marketing strategy': 'मार्केटिंग रणनीति बनाने से पहले उत्पाद चुनें या जोड़ें', 'Marketing AI strategy generated': 'मार्केटिंग AI रणनीति तैयार', 'Failed to generate marketing advice': 'मार्केटिंग सलाह तैयार नहीं हो सकी', 'GST compliance audit ready': 'GST अनुपालन ऑडिट तैयार', 'Failed to generate financial advice': 'वित्तीय सलाह तैयार नहीं हो सकी', 'Ask DukaanSaathi is temporarily unavailable': 'Ask DukaanSaathi अभी उपलब्ध नहीं है', 'Product deleted successfully': 'उत्पाद सफलतापूर्वक हटाया गया', 'Failed to delete product': 'उत्पाद हटाया नहीं जा सका', '{name} is out of stock!': '{name} स्टॉक में नहीं है!', 'Warning: Only {quantity} {name} left in stock!': 'चेतावनी: स्टॉक में केवल {quantity} {name} बचा है!', 'Cannot add more {name}. Only {quantity} available.': 'और {name} नहीं जोड़ सकते। केवल {quantity} उपलब्ध है।', 'Please enter customer name': 'कृपया ग्राहक का नाम दर्ज करें', 'Please add items to the bill': 'कृपया बिल में आइटम जोड़ें', 'Insufficient stock for {name}. Only {quantity} available.': '{name} के लिए पर्याप्त स्टॉक नहीं है। केवल {quantity} उपलब्ध है।', 'Bill generated successfully! 🎉': 'बिल सफलतापूर्वक बन गया! 🎉', 'Failed to generate bill': 'बिल नहीं बन सका', 'Bill downloaded successfully! 📄': 'बिल सफलतापूर्वक डाउनलोड हुआ! 📄', 'Bill printed successfully! 🖨️': 'बिल सफलतापूर्वक प्रिंट हुआ! 🖨️', 'Camera not ready yet. Please wait a second.': 'कैमरा अभी तैयार नहीं है। कृपया एक सेकंड प्रतीक्षा करें।', 'Unable to process camera frame.': 'कैमरा फ्रेम प्रोसेस नहीं हो सका।', 'Product scanned and saved to sales.json': 'उत्पाद स्कैन होकर sales.json में सेव हो गया', 'Scanner report generated': 'स्कैनर रिपोर्ट तैयार हो गई',
    'Retail command center': 'रिटेल कमांड सेंटर', 'Good Morning': 'सुप्रभात', 'Good Afternoon': 'नमस्कार', 'Good Evening': 'शुभ संध्या', 'Track revenue, identify your most selling products, and predict demand before stock runs low.': 'राजस्व ट्रैक करें, सबसे अधिक बिकने वाले उत्पाद पहचानें और स्टॉक कम होने से पहले मांग का अनुमान लगाएँ।', 'Last 14 days': 'पिछले 14 दिन', 'Last 12 weeks': 'पिछले 12 सप्ताह', 'Last 12 months': 'पिछले 12 महीने', 'Last 5 years': 'पिछले 5 वर्ष', 'Analytics Window': 'विश्लेषण अवधि', 'Revenue in View': 'दिखाई दे रहा राजस्व', 'Top Product': 'शीर्ष उत्पाद', 'Waiting for sales': 'बिक्री की प्रतीक्षा', 'No transactions yet': 'अभी कोई लेनदेन नहीं', '{count} units sold': '{count} यूनिट बिकीं', '{count} items sold': '{count} आइटम बिके', '{count} plotted points': '{count} प्लॉट पॉइंट', "Today's Sales": 'आज की बिक्री', 'Customers Today': 'आज के ग्राहक', 'Low Stock Items': 'कम स्टॉक आइटम', '{count} items': '{count} आइटम', Alert: 'अलर्ट', 'Sales Trend': 'बिक्री रुझान', Day: 'दिन', Week: 'सप्ताह', Month: 'माह', Year: 'वर्ष', 'Loading sales charts...': 'बिक्री चार्ट लोड हो रहे हैं...', 'No sales data available yet.': 'अभी बिक्री डेटा उपलब्ध नहीं है।', Revenue: 'राजस्व', 'Items Sold': 'बिके आइटम', 'Most Selling Products': 'सबसे अधिक बिकने वाले उत्पाद', 'Top products will appear after sales start.': 'बिक्री शुरू होने के बाद शीर्ष उत्पाद दिखाई देंगे।', 'Qty Sold': 'बिकी मात्रा', 'Hybrid ARIMA + SARIMA Forecast': 'हाइब्रिड ARIMA + SARIMA पूर्वानुमान', 'Select product': 'उत्पाद चुनें', 'Next 7 days': 'अगले 7 दिन', 'Next 14 days': 'अगले 14 दिन', 'Next 21 days': 'अगले 21 दिन', 'Next 30 days': 'अगले 30 दिन', 'Predicting...': 'पूर्वानुमान जारी...', 'Run Hybrid Forecast': 'हाइब्रिड पूर्वानुमान चलाएँ', 'Method: {method}': 'विधि: {method}', 'Suggested stock for next {days} days:': 'अगले {days} दिनों के लिए सुझाया स्टॉक:', 'Historical Qty': 'ऐतिहासिक मात्रा', 'Predicted Qty': 'अनुमानित मात्रा', 'Select a product and run hybrid forecast to view demand prediction.': 'मांग पूर्वानुमान देखने के लिए उत्पाद चुनें और हाइब्रिड पूर्वानुमान चलाएँ।', 'Income Tax Threshold Crossed!': 'आयकर सीमा पार हो गई!', 'Income Tax Alert — 1 Month Warning': 'आयकर चेतावनी — 1 महीने की सूचना', 'Dismiss tax alert': 'कर चेतावनी हटाएँ', 'Dismiss expiry alert': 'एक्सपायरी चेतावनी हटाएँ', 'Your FY revenue {annualRevenue} has exceeded the ₹15,00,000 threshold. Estimated income tax payable: {estimatedTax} (New Regime + 4% cess). Please consult a tax advisor.': 'आपका वित्तीय वर्ष राजस्व {annualRevenue} ₹15,00,000 की सीमा से अधिक हो गया है। अनुमानित आयकर देय: {estimatedTax} (नई व्यवस्था + 4% सेस)। कृपया कर सलाहकार से परामर्श करें।', 'At your current sales rate, your FY revenue will cross ₹15,00,000 in approximately {daysUntilCross} days. Current FY revenue: {annualRevenue} | Remaining before threshold: {remaining} | Estimated tax at threshold: {estimatedTax} (New Regime + 4% cess).': 'आपकी वर्तमान बिक्री दर पर, आपका वित्तीय वर्ष राजस्व लगभग {daysUntilCross} दिनों में ₹15,00,000 पार कर जाएगा। वर्तमान FY राजस्व: {annualRevenue} | सीमा तक शेष: {remaining} | सीमा पर अनुमानित कर: {estimatedTax} (नई व्यवस्था + 4% सेस)।', 'Expiry Alert: Replace These Foods/Beverages Soon': 'एक्सपायरी चेतावनी: इन खाद्य/पेय पदार्थों को जल्द बदलें', '{name} ({days} days expired)': '{name} ({days} दिन पहले एक्सपायर)', '{name} ({days} days left)': '{name} ({days} दिन शेष)', 'and {count} more.': 'और {count} अन्य।', 'Latest AI Product Photo': 'नवीनतम AI उत्पाद फोटो', 'Open Marketing AI': 'मार्केटिंग AI खोलें', Product: 'उत्पाद', 'Ask DukaanSaathi': 'Ask DukaanSaathi', 'Get instant answers about your inventory, sales, and more.': 'इन्वेंटरी, बिक्री और अधिक के बारे में तुरंत उत्तर पाएँ।', 'Ask Now': 'अभी पूछें', 'Quick Actions': 'त्वरित कार्य', 'Create Bill': 'बिल बनाएँ', 'Sales Analytics': 'बिक्री विश्लेषण', 'Billing History': 'बिलिंग इतिहास', 'Expiry Alerts': 'एक्सपायरी अलर्ट', 'New Customer': 'नया ग्राहक', 'Scanning...': 'स्कैन हो रहा है...', 'Scan Product': 'उत्पाद स्कैन करें', 'Generating...': 'तैयार हो रहा है...', 'Scan Report': 'स्कैन रिपोर्ट', 'Scanner Output': 'स्कैनर आउटपुट', 'Latest Scan JSON': 'नवीनतम स्कैन JSON', 'Latest Report': 'नवीनतम रिपोर्ट', 'Manage Products': 'उत्पाद प्रबंधित करें', 'Add Product': 'उत्पाद जोड़ें', Image: 'चित्र', Category: 'श्रेणी', Price: 'कीमत', Stock: 'स्टॉक', GST: 'GST', Actions: 'क्रियाएँ', 'No Image': 'कोई चित्र नहीं', 'Expiry:': 'एक्सपायरी:', Yes: 'हाँ', No: 'नहीं', 'Admin Billing': 'एडमिन बिलिंग', 'Create New Bill': 'नया बिल बनाएँ', 'All Bills': 'सभी बिल', 'Bill ID': 'बिल ID', Customer: 'ग्राहक', Items: 'आइटम', Subtotal: 'उप-योग', Total: 'कुल', Payment: 'भुगतान', Date: 'तारीख', 'Walk-in Customer': 'वॉक-इन ग्राहक', 'View Bill': 'बिल देखें', 'Download Bill': 'बिल डाउनलोड करें', 'Print Bill': 'बिल प्रिंट करें', 'Reports & Visualizations': 'रिपोर्ट और विज़ुअलाइज़ेशन', 'Transaction History': 'लेनदेन इतिहास', 'Transaction ID': 'लेनदेन ID', Amount: 'राशि', 'Payment Method': 'भुगतान विधि',
    'Marketing Agent AI': 'मार्केटिंग एजेंट AI', 'Generate Strategy': 'रणनीति बनाएँ', 'Latest Product:': 'नवीनतम उत्पाद:', 'Price:': 'कीमत:', 'Stock:': 'स्टॉक:', 'Photo Style': 'फोटो शैली', 'Studio White': 'स्टूडियो व्हाइट', 'Dark Luxury': 'डार्क लग्ज़री', 'Lifestyle Desk': 'लाइफस्टाइल डेस्क', 'Regenerate Product Photo': 'उत्पाद फोटो फिर बनाएँ', 'Strategy Engine:': 'रणनीति इंजन:', 'Objective:': 'उद्देश्य:', 'Target Audience:': 'लक्षित ग्राहक:', 'Value Hook:': 'वैल्यू हुक:', 'CTA:': 'CTA:', 'AI Product Photography': 'AI उत्पाद फोटोग्राफी', 'Recommended Channels': 'सुझाए गए चैनल', 'Offer Ideas': 'ऑफर आइडिया', 'Content Ideas': 'कंटेंट आइडिया', 'Add a product and generate a marketing strategy to see campaign suggestions here.': 'यहाँ अभियान सुझाव देखने के लिए एक उत्पाद जोड़ें और मार्केटिंग रणनीति बनाएँ।', 'Website help only. Ask about features, workflows, and troubleshooting in this app.': 'केवल वेबसाइट सहायता। इस ऐप की विशेषताओं, वर्कफ़्लो और समस्या समाधान के बारे में पूछें।', 'Thinking...': 'सोच रहा है...', 'Ask about DukaanSaathi website usage': 'DukaanSaathi वेबसाइट उपयोग के बारे में पूछें', Ask: 'पूछें',
    'GST Compliance Advisor (India)': 'GST अनुपालन सलाहकार (भारत)', 'This advisor automatically analyzes your product catalog, billing transactions, GST rates, and inventory-linked sales records. It then gives clear GST compliance recommendations for small Indian businesses.': 'यह सलाहकार आपके उत्पाद कैटलॉग, बिलिंग लेनदेन, GST दरों और इन्वेंटरी से जुड़े बिक्री रिकॉर्ड का स्वतः विश्लेषण करता है। इसके बाद यह छोटे भारतीय व्यवसायों के लिए स्पष्ट GST अनुपालन सुझाव देता है।', 'Analyzing...': 'विश्लेषण हो रहा है...', 'Run GST Compliance Audit': 'GST अनुपालन ऑडिट चलाएँ', 'Compliance Summary ({period})': 'अनुपालन सारांश ({period})', 'Products analyzed:': 'विश्लेषित उत्पाद:', 'Invoices analyzed:': 'विश्लेषित चालान:', 'Taxable turnover:': 'कर योग्य टर्नओवर:', 'Output GST from invoices:': 'चालानों से आउटपुट GST:', 'Potential underpaid GST:': 'संभावित कम चुकाया गया GST:', 'Potential excess charged GST:': 'संभावित अतिरिक्त वसूला गया GST:', 'Rule Coverage': 'नियम कवरेज', 'Coverage:': 'कवरेज:', '{count}/10 rules applied': '{count}/10 नियम लागू', 'All rules covered': 'सभी नियम कवर', 'Review remaining rules': 'शेष नियम देखें', 'Compliance Issues': 'अनुपालन समस्याएँ', 'Compliance Issue:': 'अनुपालन समस्या:', 'Explanation of Rule:': 'नियम की व्याख्या:', 'Risk Level:': 'जोखिम स्तर:', 'Suggested Action:': 'सुझाई गई कार्रवाई:', 'Estimated Tax Impact:': 'अनुमानित कर प्रभाव:', 'Regulation:': 'नियम:', 'Invoice Rate Mismatch Sample': 'चालान दर असमानता नमूना', 'Transactions Above Rs. 50,000 (E-Way Bill Check)': '₹50,000 से ऊपर के लेनदेन (E-Way बिल जाँच)',
    'Product Scanner': 'उत्पाद स्कैनर', 'Use your webcam to scan product labels and store structured JSON in sales.json.': 'उत्पाद लेबल स्कैन करने और sales.json में संरचित JSON सहेजने के लिए अपना वेबकैम उपयोग करें।', 'Processing...': 'प्रोसेस हो रहा है...', 'Generate Report': 'रिपोर्ट बनाएँ', 'Tip: Open camera, align label, then tap Capture & Scan.': 'सुझाव: कैमरा खोलें, लेबल सीधा रखें, फिर कैप्चर और स्कैन दबाएँ।', 'Digital Twin View': 'डिजिटल ट्विन दृश्य', '3D twin is simplified on this device for better performance.': 'बेहतर प्रदर्शन के लिए इस डिवाइस पर 3D ट्विन को सरल किया गया है।', 'Store Mirror': 'स्टोर मिरर', 'Live retail snapshot': 'लाइव रिटेल स्नैपशॉट', 'Use this view to monitor sales momentum, stock pressure, and your top-selling product in one place.': 'इस दृश्य का उपयोग बिक्री की गति, स्टॉक दबाव और शीर्ष उत्पाद को एक ही जगह पर देखने के लिए करें।', 'Revenue in current view': 'वर्तमान दृश्य का राजस्व', 'Recent days': 'हाल के दिन', 'Selected reporting window': 'चयनित रिपोर्टिंग अवधि', 'Top product': 'शीर्ष उत्पाद', 'No sales yet': 'अभी बिक्री नहीं', 'Start billing to see product demand': 'उत्पाद मांग देखने के लिए बिलिंग शुरू करें', 'Low stock pressure': 'कम स्टॉक दबाव', 'Items need restocking soon': 'आइटम को जल्द रीस्टॉक करना होगा', 'Inventory looks healthy': 'इन्वेंटरी ठीक दिख रही है', 'Operational Controls': 'ऑपरेशनल कंट्रोल', 'Open Reports': 'रिपोर्ट खोलें', 'Review Stock': 'स्टॉक देखें',
    'Add New Product': 'नया उत्पाद जोड़ें', 'Product Name': 'उत्पाद नाम', 'Enter product name': 'उत्पाद नाम दर्ज करें', 'Select Category': 'श्रेणी चुनें', Description: 'विवरण', 'Enter product description': 'उत्पाद विवरण दर्ज करें', 'Price (₹)': 'कीमत (₹)', 'Stock Quantity': 'स्टॉक मात्रा', 'Expiry Date': 'समाप्ति तिथि', 'GST Applicable': 'GST लागू', 'Product Image': 'उत्पाद चित्र', 'Loading admin dashboard...': 'एडमिन डैशबोर्ड लोड हो रहा है...', 'Back to dashboard': 'डैशबोर्ड पर वापस', Reports: 'रिपोर्ट', Scanner: 'स्कैनर', 'Quick mobile actions': 'त्वरित मोबाइल कार्य', 'View digital twin': 'डिजिटल ट्विन देखें', 'Create bill': 'बिल बनाएँ', 'Capture Product': 'उत्पाद कैप्चर करें', 'Close scanner camera': 'स्कैनर कैमरा बंद करें', Cancel: 'रद्द करें', 'Capture & Scan': 'कैप्चर और स्कैन', 'Update Product': 'उत्पाद अपडेट करें', 'Customer Name *': 'ग्राहक नाम *', 'Enter customer name': 'ग्राहक नाम दर्ज करें', 'Sale Date *': 'बिक्री तिथि *', 'Customer Phone': 'ग्राहक फोन', 'Enter customer phone': 'ग्राहक फोन दर्ज करें', 'Customer Email': 'ग्राहक ईमेल', 'Enter customer email': 'ग्राहक ईमेल दर्ज करें', cash: 'नकद', card: 'कार्ड', upi: 'UPI', bank_transfer: 'बैंक ट्रांसफर', 'Apply GST (18%)': 'GST लागू करें (18%)', 'Add Products': 'उत्पाद जोड़ें', 'Select a product to add': 'जोड़ने के लिए उत्पाद चुनें', 'No items added yet. Select products above to add them.': 'अभी कोई आइटम नहीं जोड़ा गया। ऊपर से उत्पाद चुनें।', '₹{price} each': 'प्रति ₹{price}', Notes: 'नोट्स', 'Any additional notes...': 'कोई अतिरिक्त नोट्स...', 'Generate Bill': 'बिल बनाएँ', Close: 'बंद करें', 'Quality Products & Gifts': 'गुणवत्तापूर्ण उत्पाद और उपहार', Time: 'समय', Phone: 'फोन', 'No items found': 'कोई आइटम नहीं मिला', TOTAL: 'कुल', 'Thank you for shopping with DukaanSaathi!': 'DukaanSaathi से खरीदारी के लिए धन्यवाद!', 'Visit us again for more amazing products': 'और बेहतरीन उत्पादों के लिए फिर आइए', 'Contact: +91 XXXXXXXXXX | Email: info@dukaansaathi.com': 'संपर्क: +91 XXXXXXXXXX | ईमेल: info@dukaansaathi.com', 'Correct GST slab per product': 'प्रत्येक उत्पाद के लिए सही GST स्लैब', 'Incorrect GST rate in invoices': 'चालानों में गलत GST दर', 'Missing or incorrect HSN codes': 'गुम या गलत HSN कोड', 'GST registration threshold eligibility': 'GST पंजीकरण सीमा पात्रता', 'Composition scheme eligibility': 'कम्पोज़िशन योजना पात्रता', 'E-Way bill requirement above Rs. 50,000': '₹50,000 से ऊपर E-Way बिल आवश्यकता', 'Input Tax Credit opportunities': 'इनपुट टैक्स क्रेडिट अवसर', 'Filing obligations (GSTR-1 and GSTR-3B)': 'फाइलिंग दायित्व (GSTR-1 और GSTR-3B)', 'Tax risk or penalty exposure': 'कर जोखिम या जुर्माना जोखिम', 'Actionable compliance steps': 'कार्रवाई योग्य अनुपालन कदम'
  },
  kn: {
    English: 'ಇಂಗ್ಲಿಷ್', Hindi: 'ಹಿಂದಿ', Kannada: 'ಕನ್ನಡ', Home: 'ಮುಖಪುಟ', Dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', Back: 'ಹಿಂದೆ', Login: 'ಲಾಗಿನ್', Logout: 'ಲಾಗ್‌ಔಟ್',
    'Logged out successfully': 'ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್‌ಔಟ್ ಆಗಿದೆ', 'Hi, {name}': 'ನಮಸ್ಕಾರ, {name}', 'Toggle navigation menu': 'ನ್ಯಾವಿಗೇಶನ್ ಮೆನು ತೆರೆಯಿರಿ', 'Go back': 'ಹಿಂದಕ್ಕೆ ಹೋಗಿ', Warning: 'ಎಚ್ಚರಿಕೆ', 'Dismiss notification': 'ಸೂಚನೆಯನ್ನು ಮುಚ್ಚಿ',
    'Welcome to DukaanSaathi': 'DukaanSaathi ಗೆ ಸ್ವಾಗತ', 'Loading your shopping experience...': 'ನಿಮ್ಮ ಖರೀದಿ ಅನುಭವ ಲೋಡ್ ಆಗುತ್ತಿದೆ...', '3D effects disabled on this device': 'ಈ ಸಾಧನದಲ್ಲಿ 3D ಪರಿಣಾಮಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    'Run Your Shop Smarter with AI': 'AI ಸಹಾಯದಿಂದ ನಿಮ್ಮ ಅಂಗಡಿಯನ್ನು ಇನ್ನಷ್ಟು ಚತುರವಾಗಿ ನಡೆಸಿ', 'Select your preferred language': 'ನಿಮ್ಮ ಇಚ್ಛಿತ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', 'Language selector': 'ಭಾಷೆ ಆಯ್ಕೆ', 'Get Started': 'ಪ್ರಾರಂಭಿಸಿ',
    "By continuing, you agree to DukaanSaathi's Terms of Service and Privacy Policy.": 'ಮುಂದುವರಿಸುವ ಮೂಲಕ DukaanSaathi ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಗೆ ನೀವು ಒಪ್ಪುತ್ತೀರಿ.',
    'Built for modern retailers': 'ಆಧುನಿಕ ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿಗಳಿಗೆ ನಿರ್ಮಿಸಲಾಗಿದೆ', 'Inventory, billing, and AI recommendations in one workflow.': 'ಒಂದು ವರ್ಕ್‌ಫ್ಲೋದಲ್ಲೇ ಇನ್‌ವೆಂಟರಿ, ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು AI ಶಿಫಾರಸುಗಳು.', 'Browse Products': 'ಉತ್ಪನ್ನಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'Welcome back!': 'ಮತ್ತೆ ಸ್ವಾಗತ!', 'Login failed. Please try again.': 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', 'Account created! Welcome to DukaanSaathi.': 'ಖಾತೆ ರಚಿಸಲಾಗಿದೆ! DukaanSaathi ಗೆ ಸ್ವಾಗತ.', 'Registration failed. Please try again.': 'ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'Create Account': 'ಖಾತೆ ರಚಿಸಿ', 'Sign In': 'ಸೈನ್ ಇನ್', 'Create Retailer Account': 'ರಿಟೈಲರ್ ಖಾತೆ ರಚಿಸಿ', 'Register with your email to manage your shop with DukaanSaathi.': 'DukaanSaathi ಮೂಲಕ ನಿಮ್ಮ ಅಂಗಡಿಯನ್ನು ನಿರ್ವಹಿಸಲು ಇಮೇಲ್ ಬಳಸಿ ನೋಂದಾಯಿಸಿ.', 'Full Name': 'ಪೂರ್ಣ ಹೆಸರು', Email: 'ಇಮೇಲ್', Password: 'ಪಾಸ್‌ವರ್ಡ್', 'Your full name': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು', 'Min. 6 characters': 'ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು', 'Creating account...': 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...', 'Already have an account?': 'ಈಗಾಗಲೇ ಖಾತೆಯಿದೆಯೇ?', 'Retailer Sign In': 'ರಿಟೈಲರ್ ಸೈನ್ ಇನ್', 'Sign in to manage your retail shop.': 'ನಿಮ್ಮ ಚಿಲ್ಲರೆ ಅಂಗಡಿಯನ್ನು ನಿರ್ವಹಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.', 'Enter your email': 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ', 'Enter your password': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ', 'Signing in...': 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...', 'New here?': 'ಹೊಸಬರೇ?', 'Create an account': 'ಖಾತೆ ರಚಿಸಿ',
    Notifications: 'ಅಧಿಸೂಚನೆಗಳು', 'Clear all': 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ', Dismiss: 'ಮುಚ್ಚಿ', 'All clear! No new alerts.': 'ಎಲ್ಲವೂ ಸ್ಪಷ್ಟ! ಹೊಸ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.', 'Dismiss all': 'ಎಲ್ಲವನ್ನೂ ಮುಚ್ಚಿ', 'Notifications — {count} unread': 'ಅಧಿಸೂಚನೆಗಳು — {count} ಓದದವು',
    'GST Planning Reminder': 'GST ಯೋಜನಾ ನೆನಪು', 'Estimate your quarterly GST liability using Finance AI before month-end to avoid surprises.': 'ಅಚ್ಚರಿಗಳನ್ನು ತಪ್ಪಿಸಲು ತಿಂಗಳ ಅಂತ್ಯಕ್ಕೂ ಮುನ್ನ Finance AI ಬಳಸಿ ನಿಮ್ಮ ತ್ರೈಮಾಸಿಕ GST ಬಾಧ್ಯತೆಯನ್ನು ಅಂದಾಜಿಸಿ.', Finance: 'ಹಣಕಾಸು', 'Income Tax Insight': 'ಆದಾಯ ತೆರಿಗೆ ಮಾಹಿತಿ', 'New regime: No income tax up to ₹12 lakh. Use Finance AI to simulate your exact tax slab.': 'ಹೊಸ ವ್ಯವಸ್ಥೆ: ₹12 ಲಕ್ಷದವರೆಗೆ ಆದಾಯ ತೆರಿಗೆ ಇಲ್ಲ. ನಿಮ್ಮ ನಿಖರ ತೆರಿಗೆ ಸ್ಲ್ಯಾಬ್ ನೋಡಲು Finance AI ಬಳಸಿ.', Tax: 'ತೆರಿಗೆ', 'AI Campaign Ready': 'AI ಅಭಿಯಾನ ಸಿದ್ಧ', 'Add any product and instantly get AI product photography + a full launch campaign strategy.': 'ಯಾವುದೇ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ ಮತ್ತು ತಕ್ಷಣ AI ಉತ್ಪನ್ನ ಫೋಟೋಗ್ರಫಿ ಹಾಗೂ ಪೂರ್ಣ ಲಾಂಚ್ ಅಭಿಯಾನ ತಂತ್ರವನ್ನು ಪಡೆಯಿರಿ.', Marketing: 'ಮಾರ್ಕೆಟಿಂಗ್', 'Boost Weekend Sales': 'ವಾರಾಂತ್ಯ ಮಾರಾಟವನ್ನು ಹೆಚ್ಚಿಸಿ', 'Bundle 2–3 related products as a combo deal — retailers typically see a 15–20% sales lift.': '2–3 ಸಂಬಂಧಿತ ಉತ್ಪನ್ನಗಳನ್ನು ಕಾಂಬೋ ಆಫರ್ ಆಗಿ ಕೊಡಿ — ಸಾಮಾನ್ಯವಾಗಿ 15–20% ಮಾರಾಟ ಹೆಚ್ಚಳ ಕಾಣಬಹುದು.', Tip: 'ಸಲಹೆ', 'Festive Season Strategy': 'ಹಬ್ಬದ ತಂತ್ರ', 'Build WhatsApp broadcast lists now. Festive outreach gets 3× better open rates than email.': 'ಇವಾಗಲೇ WhatsApp ಪ್ರಸಾರ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ. ಹಬ್ಬದ ಸಮಯದಲ್ಲಿ WhatsApp ಗೆ ಇಮೇಲ್‌ಗಿಂತ 3 ಪಟ್ಟು ಉತ್ತಮ ಓಪನ್ ರೇಟ್ ಸಿಗುತ್ತದೆ.', 'Input GST Credit': 'ಇನ್‌ಪುಟ್ GST ಕ್ರೆಡಿಟ್', 'Reconcile your purchase invoices this week to maximise your eligible input GST credit claims.': 'ಅರ್ಹ ಇನ್‌ಪುಟ್ GST ಕ್ರೆಡಿಟ್ ಹೆಚ್ಚಿಸಲು ಈ ವಾರವೇ ಖರೀದಿ ಇನ್ವಾಯ್ಸ್‌ಗಳನ್ನು ಹೊಂದಿಸಿ.', Inventory: 'ಇನ್‌ವೆಂಟರಿ', 'Low Stock: {name}': 'ಕಡಿಮೆ ಸ್ಟಾಕ್: {name}', 'Only {quantity} unit left. Restock before you run out.': 'ಕೆವಲ {quantity} ಯುನಿಟ್ ಉಳಿದಿದೆ. ಮುಗಿಯುವ ಮೊದಲು ಮರುಸ್ಟಾಕ್ ಮಾಡಿ.', 'Only {quantity} units left. Restock before you run out.': 'ಕೆವಲ {quantity} ಯುನಿಟ್‌ಗಳು ಉಳಿದಿವೆ. ಮುಗಿಯುವ ಮೊದಲು ಮರುಸ್ಟಾಕ್ ಮಾಡಿ.',
    'You are not authorized to view this page.': 'ಈ ಪುಟವನ್ನು ನೋಡಲು ನಿಮಗೆ ಅನುಮತಿ ಇಲ್ಲ.', 'Failed to load products': 'ಉತ್ಪನ್ನಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ', 'Failed to fetch dashboard stats': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅಂಕಿಅಂಶಗಳನ್ನು ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ', 'Failed to load bills': 'ಬಿಲ್ಲುಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ', 'Failed to load sales analytics': 'ಮಾರಾಟ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ', 'Selected product no longer exists. Switched to first available product.': 'ಆಯ್ಕೆ ಮಾಡಿದ ಉತ್ಪನ್ನ ಈಗ ಲಭ್ಯವಿಲ್ಲ. ಮೊದಲ ಲಭ್ಯ ಉತ್ಪನ್ನಕ್ಕೆ ಬದಲಾಯಿಸಲಾಗಿದೆ.', 'Failed to generate ARIMA forecast': 'ARIMA ಪೂರ್ವಾನುಮಾನ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ', 'Product updated successfully': 'ಉತ್ಪನ್ನ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ', 'Product added successfully': 'ಉತ್ಪನ್ನ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ', 'Failed to submit product': 'ಉತ್ಪನ್ನ ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ', 'Add or select a product first to generate marketing strategy': 'ಮಾರ್ಕೆಟಿಂಗ್ ತಂತ್ರ ರಚಿಸಲು ಮೊದಲು ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಸೇರಿಸಿ', 'Marketing AI strategy generated': 'ಮಾರ್ಕೆಟಿಂಗ್ AI ತಂತ್ರ ಸಿದ್ಧವಾಗಿದೆ', 'Failed to generate marketing advice': 'ಮಾರ್ಕೆಟಿಂಗ್ ಸಲಹೆ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ', 'GST compliance audit ready': 'GST ಅನುಗುಣತೆ ಆಡಿಟ್ ಸಿದ್ಧವಾಗಿದೆ', 'Failed to generate financial advice': 'ಹಣಕಾಸು ಸಲಹೆ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ', 'Ask DukaanSaathi is temporarily unavailable': 'Ask DukaanSaathi ತಾತ್ಕಾಲಿಕವಾಗಿ ಲಭ್ಯವಿಲ್ಲ', 'Product deleted successfully': 'ಉತ್ಪನ್ನ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ', 'Failed to delete product': 'ಉತ್ಪನ್ನ ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ', '{name} is out of stock!': '{name} ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಇಲ್ಲ!', 'Warning: Only {quantity} {name} left in stock!': 'ಎಚ್ಚರಿಕೆ: ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಕೆವಲ {quantity} {name} ಮಾತ್ರ ಉಳಿದಿದೆ!', 'Cannot add more {name}. Only {quantity} available.': 'ಹೆಚ್ಚುವರಿ {name} ಸೇರಿಸಲಾಗುವುದಿಲ್ಲ. ಕೆವಲ {quantity} ಮಾತ್ರ ಲಭ್ಯ.', 'Please enter customer name': 'ದಯವಿಟ್ಟು ಗ್ರಾಹಕರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ', 'Please add items to the bill': 'ದಯವಿಟ್ಟು ಬಿಲ್ಲಿಗೆ ಐಟಂಗಳನ್ನು ಸೇರಿಸಿ', 'Insufficient stock for {name}. Only {quantity} available.': '{name} ಗೆ ಸಾಕಷ್ಟು ಸ್ಟಾಕ್ ಇಲ್ಲ. ಕೆವಲ {quantity} ಮಾತ್ರ ಲಭ್ಯ.', 'Bill generated successfully! 🎉': 'ಬಿಲ್ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ! 🎉', 'Failed to generate bill': 'ಬಿಲ್ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ', 'Bill downloaded successfully! 📄': 'ಬಿಲ್ ಯಶಸ್ವಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಯಿತು! 📄', 'Bill printed successfully! 🖨️': 'ಬಿಲ್ ಯಶಸ್ವಿಯಾಗಿ ಮುದ್ರಿಸಲಾಗಿದೆ! 🖨️', 'Camera not ready yet. Please wait a second.': 'ಕ್ಯಾಮೆರಾ ಇನ್ನೂ ಸಿದ್ಧವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಒಂದು ಕ್ಷಣ ಕಾಯಿರಿ.', 'Unable to process camera frame.': 'ಕ್ಯಾಮೆರಾ ಫ್ರೇಮ್ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.', 'Product scanned and saved to sales.json': 'ಉತ್ಪನ್ನ ಸ್ಕ್ಯಾನ್ ಆಗಿ sales.json ಗೆ ಉಳಿಸಲಾಗಿದೆ', 'Scanner report generated': 'ಸ್ಕ್ಯಾನರ್ ವರದಿ ರಚಿಸಲಾಗಿದೆ',
    'Retail command center': 'ರಿಟೇಲ್ ಕಮಾಂಡ್ ಸೆಂಟರ್', 'Good Morning': 'ಶುಭೋದಯ', 'Good Afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ', 'Good Evening': 'ಶುಭ ಸಂಜೆ', 'Track revenue, identify your most selling products, and predict demand before stock runs low.': 'ಆದಾಯವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಹೆಚ್ಚು ಮಾರಾಟವಾಗುವ ಉತ್ಪನ್ನಗಳನ್ನು ಗುರುತಿಸಿ, ಸ್ಟಾಕ್ ಕಡಿಮೆಯಾಗುವ ಮೊದಲು ಬೇಡಿಕೆಯನ್ನು ಊಹಿಸಿ.', 'Last 14 days': 'ಕಳೆದ 14 ದಿನಗಳು', 'Last 12 weeks': 'ಕಳೆದ 12 ವಾರಗಳು', 'Last 12 months': 'ಕಳೆದ 12 ತಿಂಗಳುಗಳು', 'Last 5 years': 'ಕಳೆದ 5 ವರ್ಷಗಳು', 'Analytics Window': 'ವಿಶ್ಲೇಷಣಾ ಅವಧಿ', 'Revenue in View': 'ದೃಶ್ಯದಲ್ಲಿರುವ ಆದಾಯ', 'Top Product': 'ಅತ್ಯುತ್ತಮ ಉತ್ಪನ್ನ', 'Waiting for sales': 'ಮಾರಾಟಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದೆ', 'No transactions yet': 'ಇನ್ನೂ ವ್ಯವಹಾರಗಳಿಲ್ಲ', '{count} units sold': '{count} ಯುನಿಟ್ ಮಾರಾಟವಾಗಿದೆ', '{count} items sold': '{count} ಐಟಂ ಮಾರಾಟವಾಗಿದೆ', '{count} plotted points': '{count} ಚಾರ್ಟ್ ಪಾಯಿಂಟ್‌ಗಳು', "Today's Sales": 'ಇಂದಿನ ಮಾರಾಟ', 'Customers Today': 'ಇಂದಿನ ಗ್ರಾಹಕರು', 'Low Stock Items': 'ಕಡಿಮೆ ಸ್ಟಾಕ್ ಐಟಂಗಳು', '{count} items': '{count} ಐಟಂಗಳು', Alert: 'ಎಚ್ಚರಿಕೆ', 'Sales Trend': 'ಮಾರಾಟ ಪ್ರವೃತ್ತಿ', Day: 'ದಿನ', Week: 'ವಾರ', Month: 'ತಿಂಗಳು', Year: 'ವರ್ಷ', 'Loading sales charts...': 'ಮಾರಾಟ ಚಾರ್ಟ್‌ಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...', 'No sales data available yet.': 'ಇನ್ನೂ ಮಾರಾಟದ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.', Revenue: 'ಆದಾಯ', 'Items Sold': 'ಮಾರಾಟವಾದ ಐಟಂಗಳು', 'Most Selling Products': 'ಅತ್ಯಧಿಕ ಮಾರಾಟವಾಗುವ ಉತ್ಪನ್ನಗಳು', 'Top products will appear after sales start.': 'ಮಾರಾಟ ಆರಂಭವಾದ ನಂತರ ಅತ್ಯುತ್ತಮ ಉತ್ಪನ್ನಗಳು ಕಾಣಿಸುತ್ತವೆ.', 'Qty Sold': 'ಮಾರಾಟ ಪ್ರಮಾಣ', 'Hybrid ARIMA + SARIMA Forecast': 'ಹೈಬ್ರಿಡ್ ARIMA + SARIMA ಪೂರ್ವಾನುಮಾನ', 'Select product': 'ಉತ್ಪನ್ನ ಆಯ್ಕೆಮಾಡಿ', 'Next 7 days': 'ಮುಂದಿನ 7 ದಿನಗಳು', 'Next 14 days': 'ಮುಂದಿನ 14 ದಿನಗಳು', 'Next 21 days': 'ಮುಂದಿನ 21 ದಿನಗಳು', 'Next 30 days': 'ಮುಂದಿನ 30 ದಿನಗಳು', 'Predicting...': 'ಊಹಿಸಲಾಗುತ್ತಿದೆ...', 'Run Hybrid Forecast': 'ಹೈಬ್ರಿಡ್ ಪೂರ್ವಾನುಮಾನ ಚಾಲನೆ ಮಾಡಿ', 'Method: {method}': 'ವಿಧಾನ: {method}', 'Suggested stock for next {days} days:': 'ಮುಂದಿನ {days} ದಿನಗಳಿಗೆ ಶಿಫಾರಸು ಮಾಡಿದ ಸ್ಟಾಕ್:', 'Historical Qty': 'ಐತಿಹಾಸಿಕ ಪ್ರಮಾಣ', 'Predicted Qty': 'ಊಹಿಸಿದ ಪ್ರಮಾಣ', 'Select a product and run hybrid forecast to view demand prediction.': 'ಬೇಡಿಕೆ ಪೂರ್ವಾನುಮಾನ ನೋಡಲು ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಹೈಬ್ರಿಡ್ ಪೂರ್ವಾನುಮಾನವನ್ನು ಚಾಲನೆ ಮಾಡಿ.', 'Income Tax Threshold Crossed!': 'ಆದಾಯ ತೆರಿಗೆ ಮಿತಿ ದಾಟಿದೆ!', 'Income Tax Alert — 1 Month Warning': 'ಆದಾಯ ತೆರಿಗೆ ಎಚ್ಚರಿಕೆ — 1 ತಿಂಗಳ ಮುನ್ನೋಟ', 'Dismiss tax alert': 'ತೆರಿಗೆ ಎಚ್ಚರಿಕೆಯನ್ನು ಮುಚ್ಚಿ', 'Dismiss expiry alert': 'ಅವಧಿ ಮುಕ್ತಾಯ ಎಚ್ಚರಿಕೆಯನ್ನು ಮುಚ್ಚಿ', 'Your FY revenue {annualRevenue} has exceeded the ₹15,00,000 threshold. Estimated income tax payable: {estimatedTax} (New Regime + 4% cess). Please consult a tax advisor.': 'ನಿಮ್ಮ ಹಣಕಾಸು ವರ್ಷದ ಆದಾಯ {annualRevenue} ₹15,00,000 ಮಿತಿಯನ್ನು ದಾಟಿದೆ. ಅಂದಾಜು ಆದಾಯ ತೆರಿಗೆ: {estimatedTax} (ಹೊಸ ವ್ಯವಸ್ಥೆ + 4% cess). ದಯವಿಟ್ಟು ತೆರಿಗೆ ಸಲಹೆಗಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ.', 'At your current sales rate, your FY revenue will cross ₹15,00,000 in approximately {daysUntilCross} days. Current FY revenue: {annualRevenue} | Remaining before threshold: {remaining} | Estimated tax at threshold: {estimatedTax} (New Regime + 4% cess).': 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಮಾರಾಟ ದರದಲ್ಲಿ, ನಿಮ್ಮ ಹಣಕಾಸು ವರ್ಷದ ಆದಾಯ ಸುಮಾರು {daysUntilCross} ದಿನಗಳಲ್ಲಿ ₹15,00,000 ದಾಟುತ್ತದೆ. ಪ್ರಸ್ತುತ FY ಆದಾಯ: {annualRevenue} | ಮಿತಿಗೆ ಉಳಿದಿರುವುದು: {remaining} | ಮಿತಿಯಲ್ಲಿನ ಅಂದಾಜು ತೆರಿಗೆ: {estimatedTax} (ಹೊಸ ವ್ಯವಸ್ಥೆ + 4% cess).', 'Expiry Alert: Replace These Foods/Beverages Soon': 'ಅವಧಿ ಮುಗಿಯುವ ಎಚ್ಚರಿಕೆ: ಈ ಆಹಾರ/ಪಾನೀಯಗಳನ್ನು ಬೇಗ ಬದಲಿಸಿ', '{name} ({days} days expired)': '{name} ({days} ದಿನಗಳ ಹಿಂದೆ ಅವಧಿ ಮುಗಿದಿದೆ)', '{name} ({days} days left)': '{name} ({days} ದಿನಗಳು ಉಳಿದಿವೆ)', 'and {count} more.': 'ಮತ್ತು ಇನ್ನೂ {count}.', 'Latest AI Product Photo': 'ಇತ್ತೀಚಿನ AI ಉತ್ಪನ್ನ ಫೋಟೋ', 'Open Marketing AI': 'ಮಾರ್ಕೆಟಿಂಗ್ AI ತೆರೆಯಿರಿ', Product: 'ಉತ್ಪನ್ನ', 'Ask DukaanSaathi': 'Ask DukaanSaathi', 'Get instant answers about your inventory, sales, and more.': 'ಇನ್‌ವೆಂಟರಿ, ಮಾರಾಟ ಮತ್ತು ಇನ್ನಷ್ಟು ಕುರಿತು ತಕ್ಷಣ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ.', 'Ask Now': 'ಈಗ ಕೇಳಿ', 'Quick Actions': 'ವೇಗದ ಕ್ರಮಗಳು', 'Create Bill': 'ಬಿಲ್ ರಚಿಸಿ', 'Sales Analytics': 'ಮಾರಾಟ ವಿಶ್ಲೇಷಣೆ', 'Billing History': 'ಬಿಲ್ಲಿಂಗ್ ಇತಿಹಾಸ', 'Expiry Alerts': 'ಅವಧಿ ಮುಗಿಯುವ ಎಚ್ಚರಿಕೆಗಳು', 'New Customer': 'ಹೊಸ ಗ್ರಾಹಕ', 'Scanning...': 'ಸ್ಕ್ಯಾನ್ ಆಗುತ್ತಿದೆ...', 'Scan Product': 'ಉತ್ಪನ್ನ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', 'Generating...': 'ರಚಿಸಲಾಗುತ್ತಿದೆ...', 'Scan Report': 'ಸ್ಕ್ಯಾನ್ ವರದಿ', 'Scanner Output': 'ಸ್ಕ್ಯಾನರ್ ಔಟ್‌ಪುಟ್', 'Latest Scan JSON': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್ JSON', 'Latest Report': 'ಇತ್ತೀಚಿನ ವರದಿ', 'Manage Products': 'ಉತ್ಪನ್ನಗಳನ್ನು ನಿರ್ವಹಿಸಿ', 'Add Product': 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ', Image: 'ಚಿತ್ರ', Category: 'ವರ್ಗ', Price: 'ಬೆಲೆ', Stock: 'ಸ್ಟಾಕ್', GST: 'GST', Actions: 'ಕ್ರಮಗಳು', 'No Image': 'ಚಿತ್ರವಿಲ್ಲ', 'Expiry:': 'ಅವಧಿ:', Yes: 'ಹೌದು', No: 'ಇಲ್ಲ', 'Admin Billing': 'ಅಡ್ಮಿನ್ ಬಿಲ್ಲಿಂಗ್', 'Create New Bill': 'ಹೊಸ ಬಿಲ್ ರಚಿಸಿ', 'All Bills': 'ಎಲ್ಲ ಬಿಲ್ಲುಗಳು', 'Bill ID': 'ಬಿಲ್ ID', Customer: 'ಗ್ರಾಹಕ', Items: 'ಐಟಂಗಳು', Subtotal: 'ಉಪಮೊತ್ತ', Total: 'ಒಟ್ಟು', Payment: 'ಪಾವತಿ', Date: 'ದಿನಾಂಕ', 'Walk-in Customer': 'ನೇರ ಗ್ರಾಹಕ', 'View Bill': 'ಬಿಲ್ ವೀಕ್ಷಿಸಿ', 'Download Bill': 'ಬಿಲ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', 'Print Bill': 'ಬಿಲ್ ಮುದ್ರಿಸಿ', 'Reports & Visualizations': 'ವರದಿಗಳು ಮತ್ತು ದೃಶ್ಯೀಕರಣಗಳು', 'Transaction History': 'ವ್ಯವಹಾರ ಇತಿಹಾಸ', 'Transaction ID': 'ವ್ಯವಹಾರ ID', Amount: 'ಮೊತ್ತ', 'Payment Method': 'ಪಾವತಿ ವಿಧಾನ',
    'Marketing Agent AI': 'ಮಾರ್ಕೆಟಿಂಗ್ ಏಜೆಂಟ್ AI', 'Generate Strategy': 'ತಂತ್ರ ರಚಿಸಿ', 'Latest Product:': 'ಇತ್ತೀಚಿನ ಉತ್ಪನ್ನ:', 'Price:': 'ಬೆಲೆ:', 'Stock:': 'ಸ್ಟಾಕ್:', 'Photo Style': 'ಫೋಟೋ ಶೈಲಿ', 'Studio White': 'ಸ್ಟುಡಿಯೋ ವೈಟ್', 'Dark Luxury': 'ಡಾರ್ಕ್ ಲಕ್ಸುರಿ', 'Lifestyle Desk': 'ಲೈಫ್ಸ್‌ಟೈಲ್ ಡೆಸ್ಕ್', 'Regenerate Product Photo': 'ಉತ್ಪನ್ನ ಫೋಟೋವನ್ನು ಮರುರಚಿಸಿ', 'Strategy Engine:': 'ತಂತ್ರ ಎಂಜಿನ್:', 'Objective:': 'ಉದ್ದೇಶ:', 'Target Audience:': 'ಗುರಿ ಗ್ರಾಹಕರು:', 'Value Hook:': 'ಮೌಲ್ಯ ಹೂಕ್:', 'CTA:': 'CTA:', 'AI Product Photography': 'AI ಉತ್ಪನ್ನ ಫೋಟೋಗ್ರಫಿ', 'Recommended Channels': 'ಶಿಫಾರಸು ಮಾಡಿದ ಚಾನಲ್‌ಗಳು', 'Offer Ideas': 'ಆಫರ್ ಆಲೋಚನೆಗಳು', 'Content Ideas': 'ವಿಷಯ ಆಲೋಚನೆಗಳು', 'Add a product and generate a marketing strategy to see campaign suggestions here.': 'ಇಲ್ಲಿ ಅಭಿಯಾನ ಸಲಹೆಗಳನ್ನು ನೋಡಲು ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ ಮತ್ತು ಮಾರ್ಕೆಟಿಂಗ್ ತಂತ್ರ ರಚಿಸಿ.', 'Website help only. Ask about features, workflows, and troubleshooting in this app.': 'ವೆಬ್‌ಸೈಟ್ ಸಹಾಯ ಮಾತ್ರ. ಈ ಅಪ್ಲಿಕೇಶನ್‌ನ ವೈಶಿಷ್ಟ್ಯಗಳು, ವರ್ಕ್‌ಫ್ಲೋಗಳು ಮತ್ತು ತೊಂದರೆ ನಿವಾರಣೆ ಕುರಿತು ಕೇಳಿ.', 'Thinking...': 'ಆಲೋಚಿಸುತ್ತಿದೆ...', 'Ask about DukaanSaathi website usage': 'DukaanSaathi ವೆಬ್‌ಸೈಟ್ ಬಳಕೆಯ ಬಗ್ಗೆ ಕೇಳಿ', Ask: 'ಕೇಳಿ', 'GST Compliance Advisor (India)': 'GST ಅನುಗುಣತೆ ಸಲಹೆಗಾರ (ಭಾರತ)', 'This advisor automatically analyzes your product catalog, billing transactions, GST rates, and inventory-linked sales records. It then gives clear GST compliance recommendations for small Indian businesses.': 'ಈ ಸಲಹೆಗಾರ ನಿಮ್ಮ ಉತ್ಪನ್ನ ಕ್ಯಾಟಲಾಗ್, ಬಿಲ್ಲಿಂಗ್ ವ್ಯವಹಾರಗಳು, GST ದರಗಳು ಮತ್ತು ಇನ್‌ವೆಂಟರಿ ಸಂಬಂಧಿತ ಮಾರಾಟ ದಾಖಲೆಗಳನ್ನು ಸ್ವಯಂ ವಿಶ್ಲೇಷಿಸುತ್ತಾನೆ. ನಂತರ ಅದು ಸಣ್ಣ ಭಾರತೀಯ ವ್ಯವಹಾರಗಳಿಗೆ ಸ್ಪಷ್ಟ GST ಅನುಗುಣತೆ ಸಲಹೆಗಳನ್ನು ನೀಡುತ್ತದೆ.', 'Analyzing...': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...', 'Run GST Compliance Audit': 'GST ಅನುಗುಣತೆ ಪರಿಶೀಲನೆ ಚಾಲನೆ ಮಾಡಿ', 'Compliance Summary ({period})': 'ಅನುಗುಣತೆ ಸಾರಾಂಶ ({period})', 'Products analyzed:': 'ವಿಶ್ಲೇಷಿತ ಉತ್ಪನ್ನಗಳು:', 'Invoices analyzed:': 'ವಿಶ್ಲೇಷಿತ ಇನ್ವಾಯ್ಸ್‌ಗಳು:', 'Taxable turnover:': 'ತೆರಿಗೆ ವಿಧಿಸಬಹುದಾದ ಟರ್ನೋವರ್:', 'Output GST from invoices:': 'ಇನ್ವಾಯ್ಸ್‌ಗಳಿಂದ ಔಟ್‌ಪುಟ್ GST:', 'Potential underpaid GST:': 'ಕಡಿಮೆ ಪಾವತಿಸಿದ ಸಾಧ್ಯ GST:', 'Potential excess charged GST:': 'ಹೆಚ್ಚಾಗಿ ವಿಧಿಸಿದ ಸಾಧ್ಯ GST:', 'Rule Coverage': 'ನಿಯಮ ವ್ಯಾಪ್ತಿ', 'Coverage:': 'ವ്യാപ್ತಿ:', '{count}/10 rules applied': '{count}/10 ನಿಯಮಗಳು ಅನ್ವಯಿಸಲಾಗಿದೆ', 'All rules covered': 'ಎಲ್ಲ ನಿಯಮಗಳು ಒಳಗೊಂಡಿವೆ', 'Review remaining rules': 'ಉಳಿದ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ', 'Compliance Issues': 'ಅನುಗುಣತೆ ಸಮಸ್ಯೆಗಳು', 'Compliance Issue:': 'ಅನುಗುಣತೆ ಸಮಸ್ಯೆ:', 'Explanation of Rule:': 'ನಿಯಮದ ವಿವರಣೆ:', 'Risk Level:': 'ಅಪಾಯ ಮಟ್ಟ:', 'Suggested Action:': 'ಸೂಚಿಸಿದ ಕ್ರಮ:', 'Estimated Tax Impact:': 'ಅಂದಾಜು ತೆರಿಗೆ ಪರಿಣಾಮ:', 'Regulation:': 'ನಿಯಮಾವಳಿ:', 'Invoice Rate Mismatch Sample': 'ಇನ್ವಾಯ್ಸ್ ದರ ವ್ಯತ್ಯಾಸ ಮಾದರಿ', 'Transactions Above Rs. 50,000 (E-Way Bill Check)': '₹50,000 ಕ್ಕಿಂತ ಮೇಲಿನ ವ್ಯವಹಾರಗಳು (E-Way Bill ಪರಿಶೀಲನೆ)', 'Product Scanner': 'ಉತ್ಪನ್ನ ಸ್ಕ್ಯಾನರ್', 'Use your webcam to scan product labels and store structured JSON in sales.json.': 'ಉತ್ಪನ್ನ ಲೇಬಲ್‌ಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ sales.json ನಲ್ಲಿ ರೂಪುಗೊಂಡ JSON ಅನ್ನು ಉಳಿಸಲು ನಿಮ್ಮ ವೆಬ್‌ಕ್ಯಾಮ್ ಬಳಸಿ.', 'Processing...': 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...', 'Generate Report': 'ವರದಿ ರಚಿಸಿ', 'Tip: Open camera, align label, then tap Capture & Scan.': 'ಸಲಹೆ: ಕ್ಯಾಮೆರಾವನ್ನು ತೆರೆಯಿರಿ, ಲೇಬಲ್ ಸರಿಯಾಗಿ ಹಿಡಿದು ನಂತರ Capture & Scan ಒತ್ತಿರಿ.', 'Digital Twin View': 'ಡಿಜಿಟಲ್ ಟ್ವಿನ್ ವೀಕ್ಷಣೆ', '3D twin is simplified on this device for better performance.': 'ಉತ್ತಮ ಕಾರ್ಯಕ್ಷಮತೆಗೆ ಈ ಸಾಧನದಲ್ಲಿ 3D ಟ್ವಿನ್ ಸರಳೀಕರಿಸಲಾಗಿದೆ.', 'Store Mirror': 'ಅಂಗಡಿ ಪ್ರತಿಬಿಂಬ', 'Live retail snapshot': 'ನೇರ ರಿಟೇಲ್ ಕ್ಷಣಚಿತ್ರ', 'Use this view to monitor sales momentum, stock pressure, and your top-selling product in one place.': 'ಈ ವೀಕ್ಷಣೆಯಲ್ಲಿ ಮಾರಾಟ ವೇಗ, ಸ್ಟಾಕ್ ಒತ್ತಡ ಮತ್ತು ನಿಮ್ಮ ಅತ್ಯುತ್ತಮ ಮಾರಾಟ ಉತ್ಪನ್ನವನ್ನು ಒಂದೇ ಜಾಗದಲ್ಲಿ ಗಮನಿಸಿ.', 'Revenue in current view': 'ಪ್ರಸ್ತುತ ವೀಕ್ಷಣೆಯ ಆದಾಯ', 'Recent days': 'ಇತ್ತೀಚಿನ ದಿನಗಳು', 'Selected reporting window': 'ಆಯ್ಕೆಯ ವರದಿ ಅವಧಿ', 'Top product': 'ಅತ್ಯುತ್ತಮ ಉತ್ಪನ್ನ', 'No sales yet': 'ಇನ್ನೂ ಮಾರಾಟ ಇಲ್ಲ', 'Start billing to see product demand': 'ಉತ್ಪನ್ನ ಬೇಡಿಕೆಯನ್ನು ನೋಡಲು ಬಿಲ್ಲಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ', 'Low stock pressure': 'ಕಡಿಮೆ ಸ್ಟಾಕ್ ಒತ್ತಡ', 'Items need restocking soon': 'ಐಟಂಗಳನ್ನು ಬೇಗ ಮರುಸ್ಟಾಕ್ ಮಾಡಬೇಕು', 'Inventory looks healthy': 'ಇನ್‌ವೆಂಟರಿ ಆರೋಗ್ಯಕರವಾಗಿದೆ', 'Operational Controls': 'ಕಾರ್ಯಾಚರಣೆ ನಿಯಂತ್ರಣೆಗಳು', 'Open Reports': 'ವರದಿ ತೆರೆಯಿರಿ', 'Review Stock': 'ಸ್ಟಾಕ್ ಪರಿಶೀಲಿಸಿ', 'Add New Product': 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ', 'Product Name': 'ಉತ್ಪನ್ನ ಹೆಸರು', 'Enter product name': 'ಉತ್ಪನ್ನ ಹೆಸರನ್ನು ನಮೂದಿಸಿ', 'Select Category': 'ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ', Description: 'ವಿವರಣೆ', 'Enter product description': 'ಉತ್ಪನ್ನ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ', 'Price (₹)': 'ಬೆಲೆ (₹)', 'Stock Quantity': 'ಸ್ಟಾಕ್ ಪ್ರಮಾಣ', 'Expiry Date': 'ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ', 'GST Applicable': 'GST ಅನ್ವಯ', 'Product Image': 'ಉತ್ಪನ್ನ ಚಿತ್ರ', 'Loading admin dashboard...': 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...', 'Back to dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂದಿರುಗಿ', Reports: 'ವರದಿಗಳು', Scanner: 'ಸ್ಕ್ಯಾನರ್', 'Quick mobile actions': 'ತ್ವರಿತ ಮೊಬೈಲ್ ಕ್ರಿಯೆಗಳು', 'View digital twin': 'ಡಿಜಿಟಲ್ ಟ್ವಿನ್ ವೀಕ್ಷಿಸಿ', 'Create bill': 'ಬಿಲ್ ರಚಿಸಿ', 'Capture Product': 'ಉತ್ಪನ್ನ ಸೆರೆಹಿಡಿ', 'Close scanner camera': 'ಸ್ಕ್ಯಾನರ್ ಕ್ಯಾಮೆರಾವನ್ನು ಮುಚ್ಚಿ', Cancel: 'ರದ್ದುಮಾಡಿ', 'Capture & Scan': 'ಸೆರೆಹಿಡಿದು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', 'Update Product': 'ಉತ್ಪನ್ನ ನವೀಕರಿಸಿ', 'Customer Name *': 'ಗ್ರಾಹಕ ಹೆಸರು *', 'Enter customer name': 'ಗ್ರಾಹಕ ಹೆಸರನ್ನು ನಮೂದಿಸಿ', 'Sale Date *': 'ಮಾರಾಟ ದಿನಾಂಕ *', 'Customer Phone': 'ಗ್ರಾಹಕ ಫೋನ್', 'Enter customer phone': 'ಗ್ರಾಹಕ ಫೋನ್ ನಮೂದಿಸಿ', 'Customer Email': 'ಗ್ರಾಹಕ ಇಮೇಲ್', 'Enter customer email': 'ಗ್ರಾಹಕ ಇಮೇಲ್ ನಮೂದಿಸಿ', cash: 'ನಗದು', card: 'ಕಾರ್ಡ್', upi: 'UPI', bank_transfer: 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ', 'Apply GST (18%)': 'GST ಅನ್ವಯಿಸಿ (18%)', 'Add Products': 'ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಿ', 'Select a product to add': 'ಸೇರಿಸಲು ಉತ್ಪನ್ನ ಆಯ್ಕೆಮಾಡಿ', 'No items added yet. Select products above to add them.': 'ಇನ್ನೂ ಯಾವುದೇ ಐಟಂ ಸೇರಿಸಲಿಲ್ಲ. ಮೇಲಿನಿಂದ ಉತ್ಪನ್ನಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.', '₹{price} each': 'ಪ್ರತಿ ₹{price}', Notes: 'ಟಿಪ್ಪಣಿಗಳು', 'Any additional notes...': 'ಯಾವುದೇ ಹೆಚ್ಚುವರಿ ಟಿಪ್ಪಣಿಗಳು...', 'Generate Bill': 'ಬಿಲ್ ರಚಿಸಿ', Close: 'ಮುಚ್ಚಿ', 'Quality Products & Gifts': 'ಗುಣಮಟ್ಟದ ಉತ್ಪನ್ನಗಳು ಮತ್ತು ಉಡುಗೊರೆಗಳು', Time: 'ಸಮಯ', Phone: 'ಫೋನ್', 'No items found': 'ಯಾವುದೇ ಐಟಂಗಳು ಕಂಡುಬಂದಿಲ್ಲ', TOTAL: 'ಒಟ್ಟು', 'Thank you for shopping with DukaanSaathi!': 'DukaanSaathi ನಲ್ಲಿ ಖರೀದಿಸಿದ್ದಕ್ಕೆ ಧನ್ಯವಾದಗಳು!', 'Visit us again for more amazing products': 'ಇನ್ನಷ್ಟು ಉತ್ತಮ ಉತ್ಪನ್ನಗಳಿಗಾಗಿ ಮತ್ತೆ ಬನ್ನಿ', 'Contact: +91 XXXXXXXXXX | Email: info@dukaansaathi.com': 'ಸಂಪರ್ಕ: +91 XXXXXXXXXX | ಇಮೇಲ್: info@dukaansaathi.com', 'Correct GST slab per product': 'ಪ್ರತಿ ಉತ್ಪನ್ನಕ್ಕೆ ಸರಿಯಾದ GST ಸ್ಲ್ಯಾಬ್', 'Incorrect GST rate in invoices': 'ಇನ್ವಾಯ್ಸ್‌ಗಳಲ್ಲಿ ತಪ್ಪಾದ GST ದರ', 'Missing or incorrect HSN codes': 'ಕಾಣೆಯಾದ ಅಥವಾ ತಪ್ಪಾದ HSN ಕೋಡ್‌ಗಳು', 'GST registration threshold eligibility': 'GST ನೋಂದಣಿ ಮಿತಿ ಅರ್ಹತೆ', 'Composition scheme eligibility': 'ಕಾಂಪೊಸಿಷನ್ ಯೋಜನೆ ಅರ್ಹತೆ', 'E-Way bill requirement above Rs. 50,000': '₹50,000 ಮೇಲ್ಪಟ್ಟ E-Way ಬಿಲ್ ಅಗತ್ಯ', 'Input Tax Credit opportunities': 'ಇನ್‌ಪುಟ್ ತೆರಿಗೆ ಕ್ರೆಡಿಟ್ ಅವಕಾಶಗಳು', 'Filing obligations (GSTR-1 and GSTR-3B)': 'ಫೈಲಿಂಗ್ ಬಾಧ್ಯತೆಗಳು (GSTR-1 ಮತ್ತು GSTR-3B)', 'Tax risk or penalty exposure': 'ತೆರಿಗೆ ಅಪಾಯ ಅಥವಾ ದಂಡ ಸಾಧ್ಯತೆ', 'Actionable compliance steps': 'ಕ್ರಿಯಾತ್ಮಕ ಅನುಗುಣತೆ ಹಂತಗಳು'
  }
};

const languageOptions = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
];

const localeByLanguage = {
  en: 'en-IN',
  hi: 'hi-IN',
  kn: 'kn-IN',
};

const LanguageContext = createContext(null);

function interpolate(template, vars) {
  return String(template).replace(/\{(\w+)\}/g, (_, key) => String(vars?.[key] ?? `{${key}}`));
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored && localeByLanguage[stored]) {
      return stored;
    }

    const browser = (navigator.language || '').toLowerCase();
    if (browser.startsWith('hi')) return 'hi';
    if (browser.startsWith('kn')) return 'kn';
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    locale: localeByLanguage[language] || 'en-IN',
    languageOptions,
    t: (key, vars) => {
      const localized = messages[language]?.[key] ?? messages.en[key] ?? key;
      return interpolate(localized, vars);
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};